### ISSUE TITLE
Can't view Parquet files in VSCode

### ISSUE THREAD

**Issue by snestler** [adamviola/parquet-explorer#1]
On a Windows machine, using latest version of VSCode.  Installed the parquet-explorer extension.  But get the following error when trying to view a parquet file.  Here is the error message that I receive:

<img width="779" alt="image" src="https://github.com/adamviola/parquet-explorer/assets/6753134/9c9a0f3d-9f54-4da9-819f-36933bb0832f">

**Comment by bfgdigital** [comment]
Same issue here. I've tried exploring a little but can't find the magic 'table' within the file.
Otherwise looks like a brilliant solution to viewing Parquet files in vscode.

**Comment by adamviola** [comment]
The workaround as of right now is to put the exact path to the file instead of "data". I'll look into this on my Windows machine. Thanks for the report!

**Comment by uditrana** [comment]
Same issue here

**Comment by snestler** [comment]
Not sure about how to implement your suggested solution, @adamviola.  All I am doing is single-clicking on the file I want to see in the VS Code Explorer.

**Comment by raynerz** [comment]
Same issue here

**Comment by danielearwicker** [comment]
This appears to still be an issue - would a reasonable workaround be to make the UI default to the SQL that works?

e.g.

```sql
SELECT * FROM "C:\my-app\output\incredible.parquet";
```

(Awesome extension by the way, been using it for the last week on non-Windows, only just hit this issue.)

**Comment by adamviola** [comment]
Thanks @cathaypacific8747 for the PR that fixes this! Just uploaded v1.1.0 to the marketplace
