### ISSUE TITLE
Duplicate returned rows for count operation

### ISSUE THREAD

**Issue by adscregg** [adamviola/parquet-explorer#10]
VSCode version: 1.89.1
OS: Windows

In the latest release (1.2.0) of the extension, some operations appear to duplicate the rows returned:
![image](https://github.com/adamviola/parquet-explorer/assets/50719656/11e77f4e-3653-4ba9-9841-c5c465b60ced)

This issue is not present in the previous release (1.1.0):
![image](https://github.com/adamviola/parquet-explorer/assets/50719656/57797b95-db17-4c54-845f-c50cf772cac8)

**Comment by adamviola** [comment]
Looks like we're always repeating all rows - e.g., `SELECT * FROM data LIMIT 2` returns 4 rows. Will have a fix out soon

**Comment by adamviola** [comment]
Fixed in v1.2.1!

**Comment by adscregg** [comment]
Thanks for the quick fix!
