### ISSUE TITLE
Feature Request: can you publish on the Open VSX Registry

### ISSUE THREAD

**Issue by parker-research** [adamviola/parquet-explorer#11]
Can you please publish this extension on the [Open VSX Registry](https://open-vsx.org) so that it can be installed in VSCodium (the open source non-Microsoft non-telemetry build)?

**Comment by adamviola** [comment]
[Done!](https://open-vsx.org/extension/AdamViola/parquet-explorer)

**Comment by DeflateAwning** [comment]
Very awesome, thanks a lot!
