### ISSUE TITLE
Issue with LargeUtf8 data type

### ISSUE THREAD

**Issue by snestler** [adamviola/parquet-explorer#2]
I am able to view some .parquet files in VS Code using parquet-explorer.  But it seems to have an issue with others.  Here is the error message I am getting:

{"error":"while reading {path-to-file\\filename.parquet}: Error: Unrecognized type: \"LargeUtf8\" (20)"}

Any suggestions?  Thank you.

**Comment by adamviola** [comment]
We use DuckDB to read the Parquet file, and I believe DuckDB uses Apache Arrow to read the Parquet file.

Apache Arrow actually only [recently added JavaScript support for reading LargeUtf8](https://github.com/apache/arrow/pull/35780)! Looks like it happened in version v15.0 (comparing the implementation status page of [v14.0](https://arrow.apache.org/docs/14.0/status.html) and [v15.0](https://arrow.apache.org/docs/status.html#data-types))

However, it looks like [DuckDB is using an old version of Arrow](https://github.com/duckdb/duckdb-node/blob/f9a910d544835f55dac36485d767b1c2f6aafb87/package-lock.json#L3451) v9.0.0. 

Closing for now. I'll keep an eye on the version of Arrow used by future DuckDB versions.
