### ISSUE TITLE
feat: Include column datatype under the column name

### ISSUE THREAD

**Issue by NickCrews** [adamviola/parquet-explorer#3]
Hi! Thanks for the great extension, I really love it. Would you be willing for this to come in as a new feature? Possibly under a settings flag, but I could also see this just being the default cuz it's nice. Would you be willing to do this yourself because you are familiar with the codebase, or would I need to submit a PR?

**Comment by adamviola** [comment]
I added a column type tooltip that shows when you hover over a column header as part of the [v1.2.0 release](https://github.com/adamviola/parquet-explorer/releases/tag/v1.2.0). @NickCrews lmk if you're still interested in showing under the column name. I can add a setting

**Comment by NickCrews** [comment]
Just tried out the new release, it looks awesome! The tooltip is totally adequate for me.
