### ISSUE TITLE
Make default query customizable

### ISSUE THREAD

**Issue by robjhornby-ts** [adamviola/parquet-explorer#4]
It would be neat if the default query could be defined in a VSCode setting.

For example, I'd like to customize my default query to add `LIMIT 100` to avoid loading the full dataset when I open a file

**Comment by adamviola** [comment]
FYI we `LIMIT 100` [by default](https://github.com/adamviola/parquet-explorer/blob/3df4637c02c75048eda02aff2c7cde46e54ffd6a/media/parquetExplorer.js#L52). We fetch additional batches of 100 on scroll.

But a default query is a great idea. I'll get to this eventually, no guarantees on when. Feel free to submit a PR if you'd like it sooner

**Comment by adamviola** [comment]
Added with the [v1.2.0 release](https://github.com/adamviola/parquet-explorer/releases/tag/v1.2.0)!

**Comment by robjhornby-ts** [comment]
Thank you, nice addition!
