### ISSUE TITLE
DESCRIBE function doesn't work

### ISSUE THREAD

**Issue by odedfos** [adamviola/parquet-explorer#5]
[DUCKDB support](https://duckdb.org/docs/guides/meta/describe.html) the DESCRIBE function. This is useful for inspecting the parquet schema.
When I run the command in the SQL terminal `DESCRIBE SELECT * FROM data;` I get the following error:
`Parser Error:syntax error at or near "SELECT"
 LINE 2: DESCRIBE SELECT * FROM data`

**Comment by adamviola** [comment]
Thanks @cathaypacific8747 for the PR that fixes this! Just uploaded v1.1.0 to the marketplace
