### ISSUE TITLE
Add *.pq as a parquet file extension

### ISSUE THREAD

**Issue by andreiburov** [adamviola/parquet-explorer#7]
Hi @adamviola, could you please add *.pq extension to be recognized as parquet as well?

**Comment by andreiburov** [comment]
Maybe it's better to customize it somehow, here I just added it to the selector of custom editor provider.

[AddPQExtenstion.patch](https://github.com/adamviola/parquet-explorer/files/14977906/AddPQExtenstion.patch)

**Comment by parker-research** [comment]
I'd also love this!

**Comment by adamviola** [comment]
I'll add this in the next update. There's a few things coming.

**Comment by adamviola** [comment]
Added with the [v1.2.0 release](https://github.com/adamviola/parquet-explorer/releases/tag/v1.2.0)!
